hydra:
  run:
    dir: ./experiments/${scenario}/${dataset}_${initial_increment}-${increment}-${method}
  job:
    chdir: true

  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(message)s'

class_order: "class_orders/cifar100.yaml"
dataset_root: ""
workdir: ""
log_path: "moe_cifar_imb0.01_intel(vision)random(text)freeze.json"
model_name: "ViT-B/16"
prompt_template: "a bad photo of a {}."

batch_size: 128
increment: ${initial_increment}
initial_increment: 20
scenario: "class"
dataset: "cifar100"

# method: "lwf"
# lr: 7.1e-6
# ls: 0.2
# we: 
# avg_freq:  
# ref_dataset:
# ref_sentences: 

weight_decay: 0.0
l2: 0
ce_method: 0

method: "MoE-Adapters"
lr: 1e-3
ls: 0.0
#we:
#avg_freq:
#ref_dataset:
#ref_sentences: random


imbalance: true
imb_type: "exp"      # or "step", "fewshot"
imb_factor: 0.01
imb_rand: 0

